/**
 * ============================================================================
 * ATTENDANCE WORKFLOW SERVICE
 * ============================================================================
 *
 * ⚠️ ARCHIVO AUTO-GENERADO - NO EDITAR MANUALMENTE
 *
 * Este archivo es regenerado automáticamente por WorkflowAutoGenerator.js
 * cuando cambia el código de los servicios relacionados.
 *
 * FUENTES:
 * * - LateArrivalAuthorizationService.js
 * * - CalendarioLaboralService.js
 * * - ShiftCalculatorService.js
 * * - OrganizationalHierarchyService.js
 *
 * Brain detecta este archivo via LIVE_CODE_SCAN y extrae los STAGES.
 * Cualquier cambio en los servicios fuente regenerará este archivo.
 *
 * Generado: 2025-12-14T20:58:36.149Z
 * Versión: 1.0.20251214-auto
 *
 * ============================================================================
 */

class AttendanceWorkflowService {
    /**
     * STAGES - Detectados automáticamente por Brain via LIVE_CODE_SCAN
     *
     * Fuente: Análisis de código de servicios relacionados
     * Total: 23 stages
     * Auto-generados: 14
     */
    static STAGES = {
        BIOMETRIC_CAPTURE: {
            name: 'Captura Biométrica',
            order: 1,
            category: 'identification',
            description: 'Captura de rostro en kiosko',
            transitions_to: ["IDENTIFICATION","REJECTED_QUALITY"],
            isCore: true,
        },

        IDENTIFICATION: {
            name: 'Identificación',
            order: 2,
            category: 'identification',
            description: 'Match biométrico contra BD',
            transitions_to: ["USER_VALIDATION","REJECTED_NO_MATCH"],
            isCore: true,
        },

        USER_VALIDATION: {
            name: 'Validación de Usuario',
            order: 3,
            category: 'validation',
            description: 'Verificar estado del usuario',
            transitions_to: ["SCHEDULE_VALIDATION","REJECTED_SUSPENDED"],
            isCore: true,
        },

        FIND_AUTHORIZER: {
            name: 'Find Authorizer',
            order: 4,
            category: 'authorization',
            description: 'Auto-detectado desde LateArrivalAuthorizationService.findAuthorizersByHierarchy()',
            source: {
                file: 'LateArrivalAuthorizationService.js',
                function: 'findAuthorizersByHierarchy',
                line: 314
            },
            transitions_to: [],
            isAutoGenerated: true,
        },

        VERIFY_SAME_SHIFT: {
            name: 'Verify Same Shift',
            order: 5,
            category: 'validation',
            description: 'Auto-detectado desde LateArrivalAuthorizationService.checkSupervisorSameShift()',
            source: {
                file: 'LateArrivalAuthorizationService.js',
                function: 'checkSupervisorSameShift',
                line: 541
            },
            transitions_to: ["REJECTED_ERROR_CHECKING"],
            isAutoGenerated: true,
        },

        CHECK_AVAILABILITY: {
            name: 'Check Availability',
            order: 6,
            category: 'validation',
            description: 'Auto-detectado desde LateArrivalAuthorizationService.checkSupervisorAvailability()',
            source: {
                file: 'LateArrivalAuthorizationService.js',
                function: 'checkSupervisorAvailability',
                line: 615
            },
            validations: ["result"],
            transitions_to: ["REGISTERED","REJECTED_ERROR_CHECKING"],
            isAutoGenerated: true,
        },

        ESCALATE_SAME_SHIFT: {
            name: 'Escalate Same Shift',
            order: 7,
            category: 'lookup',
            description: 'Auto-detectado desde LateArrivalAuthorizationService._findSupervisorWithSameShift()',
            source: {
                file: 'LateArrivalAuthorizationService.js',
                function: '_findSupervisorWithSameShift',
                line: 775
            },
            transitions_to: [],
            isAutoGenerated: true,
        },

        SEND_AUTHORIZATION_REQUEST: {
            name: 'Send Authorization Request',
            order: 8,
            category: 'authorization',
            description: 'Auto-detectado desde LateArrivalAuthorizationService.sendAuthorizationRequest()',
            source: {
                file: 'LateArrivalAuthorizationService.js',
                function: 'sendAuthorizationRequest',
                line: 905
            },
            transitions_to: [],
            isAutoGenerated: true,
        },

        SEND_UNIFIED_NOTIFICATION: {
            name: 'Send Unified Notification',
            order: 9,
            category: 'notification',
            description: 'Auto-detectado desde LateArrivalAuthorizationService._sendViaUnifiedNotificationSystem()',
            source: {
                file: 'LateArrivalAuthorizationService.js',
                function: '_sendViaUnifiedNotificationSystem',
                line: 1320
            },
            transitions_to: [],
            isAutoGenerated: true,
        },

        NOTIFY_EMPLOYEE_WAITING: {
            name: 'Notify Employee Waiting',
            order: 10,
            category: 'notification',
            description: 'Auto-detectado desde LateArrivalAuthorizationService._notifyEmployeeRequestSent()',
            source: {
                file: 'LateArrivalAuthorizationService.js',
                function: '_notifyEmployeeRequestSent',
                line: 1476
            },
            transitions_to: [],
            isAutoGenerated: true,
        },

        NOTIFY_AUTHORIZATION_RESULT: {
            name: 'Notify Authorization Result',
            order: 11,
            category: 'authorization',
            description: 'Auto-detectado desde LateArrivalAuthorizationService.notifyAuthorizationResult()',
            source: {
                file: 'LateArrivalAuthorizationService.js',
                function: 'notifyAuthorizationResult',
                line: 1807
            },
            transitions_to: [],
            isAutoGenerated: true,
        },

        CHECK_WORKING_DAY: {
            name: 'Check Working Day',
            order: 12,
            category: 'process',
            description: 'Auto-detectado desde CalendarioLaboralService.isWorkingDay()',
            source: {
                file: 'CalendarioLaboralService.js',
                function: 'isWorkingDay',
                line: 45
            },
            transitions_to: [],
            isAutoGenerated: true,
        },

        CHECK_HOLIDAY: {
            name: 'Check Holiday',
            order: 13,
            category: 'validation',
            description: 'Auto-detectado desde CalendarioLaboralService.checkHoliday()',
            source: {
                file: 'CalendarioLaboralService.js',
                function: 'checkHoliday',
                line: 311
            },
            validations: ["localHoliday","apiHoliday"],
            transitions_to: [],
            isAutoGenerated: true,
        },

        CHECK_COMPANY_DAY: {
            name: 'Check Company Day',
            order: 14,
            category: 'validation',
            description: 'Auto-detectado desde CalendarioLaboralService.checkCompanyNonWorkingDay()',
            source: {
                file: 'CalendarioLaboralService.js',
                function: 'checkCompanyNonWorkingDay',
                line: 397
            },
            validations: ["nonWorking.length > 0"],
            transitions_to: [],
            isAutoGenerated: true,
        },

        CALCULATE_SHIFT: {
            name: 'Calculate Shift',
            order: 15,
            category: 'process',
            description: 'Auto-detectado desde ShiftCalculatorService.calculateUserShiftForDate()',
            source: {
                file: 'ShiftCalculatorService.js',
                function: 'calculateUserShiftForDate',
                line: 34
            },
            validations: ["shift.shiftType !== 'rotative'"],
            transitions_to: [],
            isAutoGenerated: true,
        },

        GET_ESCALATION_CHAIN: {
            name: 'Get Escalation Chain',
            order: 16,
            category: 'lookup',
            description: 'Auto-detectado desde OrganizationalHierarchyService.getEscalationChain()',
            source: {
                file: 'OrganizationalHierarchyService.js',
                function: 'getEscalationChain',
                line: 105
            },
            transitions_to: [],
            isAutoGenerated: true,
        },

        GET_SUPERVISOR: {
            name: 'Get Supervisor',
            order: 17,
            category: 'lookup',
            description: 'Auto-detectado desde OrganizationalHierarchyService.getImmediateSupervisor()',
            source: {
                file: 'OrganizationalHierarchyService.js',
                function: 'getImmediateSupervisor',
                line: 125
            },
            validations: ["userQuery.length || !userQuery[0].parent_position_id","supervisorQuery.length"],
            transitions_to: [],
            isAutoGenerated: true,
        },

        REJECTED_QUALITY: {
            name: 'Rechazado - Calidad',
            order: 100,
            category: 'rejection',
            description: 'Estado final',
            transitions_to: [],
            is_final: true,
            is_rejection: true,
        },

        REJECTED_NO_MATCH: {
            name: 'Rechazado - No Match',
            order: 101,
            category: 'rejection',
            description: 'Estado final',
            transitions_to: [],
            is_final: true,
            is_rejection: true,
        },

        REJECTED_SUSPENDED: {
            name: 'Rechazado - Suspendido',
            order: 102,
            category: 'rejection',
            description: 'Estado final',
            transitions_to: [],
            is_final: true,
            is_rejection: true,
        },

        REJECTED_NO_SHIFT: {
            name: 'Rechazado - Sin Turno',
            order: 103,
            category: 'rejection',
            description: 'Estado final',
            transitions_to: [],
            is_final: true,
            is_rejection: true,
        },

        REJECTED_LATE_NO_AUTH: {
            name: 'Rechazado - Sin Autorización',
            order: 104,
            category: 'rejection',
            description: 'Estado final',
            transitions_to: [],
            is_final: true,
            is_rejection: true,
        },

        REGISTERED: {
            name: 'Fichaje Registrado',
            order: 105,
            category: 'success',
            description: 'Estado final',
            transitions_to: [],
            is_final: true,
            is_success: true,
        },

    };

    /**
     * WORKFLOW METADATA
     */
    static WORKFLOW_METADATA = {
        name: 'Workflow de Fichaje Biométrico',
        version: '1.0.20251214-auto',
        module: 'attendance',
        isAutoGenerated: true,
        generatedAt: '2025-12-14T20:58:36.149Z',
        sourceFiles: ["LateArrivalAuthorizationService.js","CalendarioLaboralService.js","ShiftCalculatorService.js","OrganizationalHierarchyService.js"],
        entry_point: 'BIOMETRIC_CAPTURE',
        final_states: {
            success: ['REGISTERED'],
            rejection: ["REJECTED_QUALITY","REJECTED_NO_MATCH","REJECTED_SUSPENDED","REJECTED_NO_SHIFT","REJECTED_LATE_NO_AUTH"]
        }
    };

    /**
     * Obtener stages en orden
     */
    static getStagesInOrder() {
        return Object.entries(this.STAGES)
            .map(([key, stage]) => ({ key, ...stage }))
            .sort((a, b) => (a.order || 999) - (b.order || 999));
    }

    /**
     * Obtener stages finales
     */
    static getFinalStages() {
        return Object.entries(this.STAGES)
            .filter(([_, stage]) => stage.is_final)
            .map(([key, stage]) => ({ key, ...stage }));
    }

    /**
     * Validar transición
     */
    static isValidTransition(fromStage, toStage) {
        const from = this.STAGES[fromStage];
        if (!from || !from.transitions_to) return false;
        return from.transitions_to.includes(toStage);
    }
}

module.exports = AttendanceWorkflowService;
